### ISSUE TITLE
16 bit output

### ISSUE THREAD

**Issue by AsgerSuhr** [AsgerSuhr/UDIM_baking#3]
currently it's not supporting 16 bit

**Comment by AsgerSuhr** [comment]
I'm not seeing any issues with saving tiles as 32 bit or 16 bit, since it's actually taking into consideration what settings you set for the original tiled image.

**Comment by Oxicid** [comment]
![8 and 16 bit diferance](https://user-images.githubusercontent.com/76912541/103942105-ebc14200-5140-11eb-9399-bb17959b46ac.gif)
despite what texture I did not create, it saves in 8 bit

**Comment by Oxicid** [comment]
8 bit - UDIM Baker 
16 bit - SP

**Comment by AsgerSuhr** [comment]
could you share your .blend file, because the way the addon works is by taking the settings from the image texture it's trying to bake to. At least that's the intended purpose.

**Comment by Oxicid** [comment]
Checked everything works

**Comment by Oxicid** [comment]
I forgot to update, that's it, now this addon fulfills its tasks for 100%, thanks a lot)

**Comment by AsgerSuhr** [comment]
ahhh great! hope it serves you well ;)
